//! S6 crash-recovery test (G4 + G5). Exercises the editor's
//! `kill -9` recovery loop: spawn the runtime stub, kill it,
//! detect via EOF + non-blocking `wait`, spawn again, re-handshake,
//! validate the connection is alive.
//!
//! Macros / shape:
//!   - Each test spins up an `IpcServer`, spawns a fresh runtime
//!     binary from `zig-out/bin/weld-runtime` (the build target this
//!     module assumes is in place), drives the handshake, kills the
//!     child, measures detection latency, then either restarts or
//!     asserts a clean exit per the gate under test.
//!   - The runtime exit path is also exercised by `editor kill -9`:
//!     the editor closes the socket, the runtime's recv-thread
//!     observes EOF, and the runtime exits with code 0.
//!
//! Linux-gated because the shared shm region cross-process pattern
//! is unreliable on macOS (see `src/core/ipc/shm_posix.zig` file
//! header). The full G4/G5 verdict lives in
//! `validation/s6-go-nogo.md` and is generated by a Linux CI run.

const std = @import("std");
const builtin = @import("builtin");

const weld_core = @import("weld_core");
const ipc = weld_core.ipc;
const framing = ipc.framing;
const messages = ipc.messages;
const platform_process = weld_core.platform.process;
const viewport = ipc.viewport;

const is_linux = builtin.os.tag == .linux;

extern "c" fn unlink(path: [*:0]const u8) c_int;
extern "c" fn shm_unlink(name: [*:0]const u8) i32;
extern "c" fn clock_gettime(clk_id: i32, tp: *timespec_t) c_int;
extern "c" fn nanosleep(req: *const timespec_t, rem: ?*timespec_t) c_int;
extern "c" fn getpid() i32;
const CLOCK_MONOTONIC: i32 = if (builtin.os.tag == .linux) 1 else 6;
const timespec_t = extern struct { tv_sec: i64, tv_nsec: i64 };

fn nowMs() i64 {
    var ts = timespec_t{ .tv_sec = 0, .tv_nsec = 0 };
    _ = clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec * 1000 + @divFloor(ts.tv_nsec, std.time.ns_per_ms);
}

fn sleepMs(ms: u64) void {
    var ts = timespec_t{
        .tv_sec = @intCast(ms / 1_000),
        .tv_nsec = @intCast((ms % 1_000) * std.time.ns_per_ms),
    };
    _ = nanosleep(&ts, null);
}

test "runtime kill -9 → editor detects EOF in <100ms" {
    if (!is_linux) return error.SkipZigTest;

    const gpa = std.testing.allocator;
    const pid = getpid();
    const socket_path = try std.fmt.allocPrintZ(gpa, "/tmp/weld-crashtest-{d}.sock", .{pid});
    defer gpa.free(socket_path);
    const shm_name = try std.fmt.allocPrintZ(gpa, "/weld-shm-crashtest-{d}", .{pid});
    defer gpa.free(shm_name);
    _ = unlink(socket_path.ptr);
    _ = shm_unlink(shm_name.ptr);
    defer _ = unlink(socket_path.ptr);
    defer _ = shm_unlink(shm_name.ptr);

    var vp = try viewport.ShmViewport.create(shm_name, viewport.default_resolution.width, viewport.default_resolution.height);
    defer vp.close();

    var server = ipc.server.IpcServer.init(gpa);
    defer server.deinit();
    try server.listen(socket_path);

    const socket_arg = try std.fmt.allocPrint(gpa, "--socket={s}", .{socket_path});
    defer gpa.free(socket_arg);
    const shm_arg = try std.fmt.allocPrint(gpa, "--shm={s}", .{shm_name});
    defer gpa.free(shm_arg);
    const pid_arg = try std.fmt.allocPrint(gpa, "--editor-pid={d}", .{pid});
    defer gpa.free(pid_arg);
    const argv = [_][]const u8{ "zig-out/bin/weld-runtime", socket_arg, shm_arg, pid_arg };

    var proc = try platform_process.spawn_process(gpa, "zig-out/bin/weld-runtime", &argv);
    try server.acceptOne();

    var hello_buf: [framing.frameSizeOf(messages.ProtocolHello)]u8 = undefined;
    _ = try server.recvHello(&hello_buf);
    try server.sendHelloAck(true, "");

    // Sleep a beat to let the runtime settle, then kill.
    sleepMs(50);
    const t0 = nowMs();
    try platform_process.kill(&proc);

    // Detect EOF on the editor side by sending a probe message and
    // expecting `error.UnexpectedEof` from the next `recvFrame`.
    var scratch: [256]u8 = undefined;
    const detect_res = server.connection().recvFrame(&scratch);
    const detect_ms = nowMs() - t0;
    try std.testing.expect(detect_ms < 100);
    try std.testing.expectError(error.UnexpectedEof, detect_res);

    // Reap.
    var reap_attempts: usize = 0;
    while (reap_attempts < 50) : (reap_attempts += 1) {
        if (try platform_process.wait_nonblock(&proc)) |_| break;
        sleepMs(10);
    }
}

test "runtime kill -9 → editor restarts + first post-restart Echo OK" {
    if (!is_linux) return error.SkipZigTest;
    // Smoke-shape: the runtime is restarted by repeating the
    // spawn_process call; we verify the new connection delivers an
    // EchoReply for an Echo we send.
    const gpa = std.testing.allocator;
    const pid = getpid();
    const socket_path = try std.fmt.allocPrintZ(gpa, "/tmp/weld-restart-{d}.sock", .{pid});
    defer gpa.free(socket_path);
    const shm_name = try std.fmt.allocPrintZ(gpa, "/weld-shm-restart-{d}", .{pid});
    defer gpa.free(shm_name);
    _ = unlink(socket_path.ptr);
    _ = shm_unlink(shm_name.ptr);
    defer _ = unlink(socket_path.ptr);
    defer _ = shm_unlink(shm_name.ptr);

    var vp = try viewport.ShmViewport.create(shm_name, viewport.default_resolution.width, viewport.default_resolution.height);
    defer vp.close();

    var server = ipc.server.IpcServer.init(gpa);
    defer server.deinit();
    try server.listen(socket_path);

    const socket_arg = try std.fmt.allocPrint(gpa, "--socket={s}", .{socket_path});
    defer gpa.free(socket_arg);
    const shm_arg = try std.fmt.allocPrint(gpa, "--shm={s}", .{shm_name});
    defer gpa.free(shm_arg);
    const pid_arg = try std.fmt.allocPrint(gpa, "--editor-pid={d}", .{pid});
    defer gpa.free(pid_arg);
    const argv = [_][]const u8{ "zig-out/bin/weld-runtime", socket_arg, shm_arg, pid_arg };

    // First spawn + handshake + kill.
    var proc = try platform_process.spawn_process(gpa, "zig-out/bin/weld-runtime", &argv);
    try server.acceptOne();
    var hbuf: [framing.frameSizeOf(messages.ProtocolHello)]u8 = undefined;
    _ = try server.recvHello(&hbuf);
    try server.sendHelloAck(true, "");
    try platform_process.kill(&proc);
    var scratch: [256]u8 = undefined;
    _ = server.connection().recvFrame(&scratch) catch {};
    // Tear down the first connection so we can accept the second.
    server.deinit();
    var reap_attempts: usize = 0;
    while (reap_attempts < 50) : (reap_attempts += 1) {
        if (try platform_process.wait_nonblock(&proc)) |_| break;
        sleepMs(10);
    }

    // Second spawn + handshake + Echo round-trip.
    server = ipc.server.IpcServer.init(gpa);
    try server.listen(socket_path);
    var proc2 = try platform_process.spawn_process(gpa, "zig-out/bin/weld-runtime", &argv);
    try server.acceptOne();
    _ = try server.recvHello(&hbuf);
    try server.sendHelloAck(true, "");

    var echo = messages.Echo{ .payload = std.mem.zeroes([64]u8) };
    for (&echo.payload, 0..) |*b, i| b.* = @intCast(i & 0xFF);
    try server.connection().sendMessage(messages.Echo, 0, &echo);
    var rep_buf: [framing.frameSizeOf(messages.EchoReply)]u8 = undefined;
    const reply = try server.connection().recvMessage(messages.EchoReply, &rep_buf);
    try std.testing.expectEqualSlices(u8, &echo.payload, &reply.payload);

    // Graceful shutdown of the second runtime.
    const sd = messages.Shutdown{};
    try server.connection().sendMessage(messages.Shutdown, 0, &sd);
    var sa_buf: [framing.frameSizeOf(messages.ShutdownAck)]u8 = undefined;
    _ = try server.connection().recvMessage(messages.ShutdownAck, &sa_buf);
    var attempts: usize = 0;
    while (attempts < 50) : (attempts += 1) {
        if (try platform_process.wait_nonblock(&proc2)) |_| break;
        sleepMs(10);
    }
}
