//! Consolidated cook — the library home of the `etch_cook` pipeline
//! (M0.8 E3-D, D-S5-etchcook-inproc). Renders N named Etch sources into ONE
//! consolidated `.zig` buffer: a shared import header, one
//! `pub const <name> = struct { ... };` namespace per input, and a `programs`
//! table mapping names to `(register, tick)` function pointers.
//!
//! Consumers:
//! - `tools/etch_cook/main.zig` — the thin CLI shim (arg parsing + file I/O)
//!   kept for the build-graph `b.addRunArtifact` cooks.
//! - `bench/etch_compile.zig` — consumes the cook IN-PROCESS (no child
//!   process on the timed path), closing the S5 subprocess-boundary debt.
//!
//! Inputs are in-memory `(name, source)` pairs — the library does no file
//! I/O, so it is host/target agnostic and trivially unit-testable.

const std = @import("std");
const parser = @import("../parser.zig");
const types = @import("../types.zig");
const diag = @import("../diagnostics.zig");
const lower = @import("lower.zig");
const errors_mod = @import("errors.zig");

/// One cook input: the Zig namespace identifier the program is wrapped in
/// (must be a valid Zig identifier) plus its Etch source bytes.
pub const NamedSource = struct {
    name: []const u8,
    source: []const u8,
};

/// Aggregate stats across every cooked input — consumed by the bench
/// harness for Gate 4 reporting (monomorphisation containment).
pub const CookStats = struct {
    rules: u32 = 0,
    distinct_signatures: u32 = 0,
};

/// Error set of the consolidated cook — the pipeline failures (parse /
/// type-check) composed with the codegen error set.
pub const ConsolidateError = error{
    OutOfMemory,
    ParseFailed,
    TypeCheckFailed,
} || errors_mod.CodegenError;

/// Cook every input into `out` (caller-owned, appended to). On the first
/// failing input the error is returned and `out` must be discarded by the
/// caller — no partial-output contract. Failure details are reported on
/// stderr attributed to the input's name (the CLI behaviour, kept so the
/// shim and the in-process consumers diagnose identically).
pub fn cookConsolidated(
    gpa: std.mem.Allocator,
    inputs: []const NamedSource,
    out: *std.ArrayListUnmanaged(u8),
) ConsolidateError!CookStats {
    try emitConsolidatedHeader(gpa, out);

    // Per-input Level-B descriptor flags (M0.8 E4) — drive the
    // `Program.write_descriptors` wiring in the programs table.
    var descriptor_flags = try gpa.alloc(bool, inputs.len);
    defer gpa.free(descriptor_flags);

    var totals: CookStats = .{};
    for (inputs, 0..) |in, idx| {
        const stats = try cookInto(gpa, in, out);
        totals.rules += stats.rules;
        totals.distinct_signatures += stats.distinct_signatures;
        descriptor_flags[idx] = stats.has_descriptors;
    }

    try emitProgramsTable(gpa, out, inputs, descriptor_flags);
    return totals;
}

fn emitConsolidatedHeader(gpa: std.mem.Allocator, buffer: *std.ArrayListUnmanaged(u8)) error{OutOfMemory}!void {
    const header =
        \\// Auto-generated by the weld_etch consolidated cook — DO NOT EDIT
        \\//
        \\// Consolidated S5 codegen output: one nested namespace per input
        \\// .etch program plus a `programs` table mapping names to
        \\// `(register, tick)` function pointers. The test driver dispatches
        \\// by name; the bench harness exercises every namespace through
        \\// the standard Zig build pipeline.
        \\
        \\const std = @import("std");
        \\const weld_core = @import("weld_core");
        \\const World = weld_core.ecs.world.World;
        \\const ComponentId = weld_core.ecs.registry.ComponentId;
        \\const FieldDesc = weld_core.ecs.registry.FieldDesc;
        \\const FieldKind = weld_core.ecs.registry.FieldKind;
        \\const DynamicArchetype = weld_core.ecs.archetype_dynamic.DynamicArchetype;
        \\const Chunk = weld_core.ecs.archetype_dynamic.Chunk;
        \\const comptime_query = weld_core.ecs.comptime_query;
        \\
        \\
    ;
    try buffer.appendSlice(gpa, header);
}

/// Per-input cook result — the bench-facing `CookStats` numbers plus the
/// Level-B descriptor flag consumed by the programs-table emission.
const InputCook = struct {
    rules: u32,
    distinct_signatures: u32,
    has_descriptors: bool,
};

fn cookInto(gpa: std.mem.Allocator, in: NamedSource, buffer: *std.ArrayListUnmanaged(u8)) ConsolidateError!InputCook {
    // Parse + type-check.
    var pr = parser.parse(gpa, in.source) catch |err| switch (err) {
        error.OutOfMemory => return error.OutOfMemory,
        else => {
            std.debug.print("cook: {s}: parse failed: {s}\n", .{ in.name, @errorName(err) });
            return error.ParseFailed;
        },
    };
    defer pr.deinit(gpa);
    if (pr.diagnostics.len > 0) {
        std.debug.print("cook: {s}: parse diagnostic: {s}\n", .{ in.name, pr.diagnostics[0].primary_message });
        return error.ParseFailed;
    }
    var diags: std.ArrayListUnmanaged(diag.Diagnostic) = .empty;
    defer {
        for (diags.items) |*d| d.deinit(gpa);
        diags.deinit(gpa);
    }
    try types.TypeChecker.check(gpa, &pr.ast, &diags);
    if (diags.items.len != 0) {
        for (diags.items) |d| std.debug.print("cook: {s}: type-check {s}: {s}\n", .{ in.name, d.code.code(), d.primary_message });
        return error.TypeCheckFailed;
    }

    // Codegen body into a scratch buffer.
    var body: std.ArrayListUnmanaged(u8) = .empty;
    defer body.deinit(gpa);
    const stats = try lower.generateFile(gpa, &pr.ast, in.name, &body);

    // Strip the per-file imports — they are emitted once at the top of the
    // consolidated file. The consolidated header above declares every
    // import the generated body relies on.
    const body_no_imports = stripImports(body.items);

    // Wrap the program in a nested namespace named after the input.
    const open = try std.fmt.allocPrint(gpa, "pub const {s} = struct {{\n", .{in.name});
    defer gpa.free(open);
    try buffer.appendSlice(gpa, open);
    try buffer.appendSlice(gpa, body_no_imports);
    try buffer.appendSlice(gpa, "};\n\n");

    return .{ .rules = stats.rules, .distinct_signatures = stats.distinct_signatures, .has_descriptors = stats.has_descriptors };
}

fn stripImports(body: []const u8) []const u8 {
    // Skip every leading line that begins with `//`, `const std =`, or
    // one of the fixed import aliases the generated bodies start with.
    // Everything after is the body proper.
    var pos: usize = 0;
    while (pos < body.len) {
        // Eat blank lines.
        while (pos < body.len and (body[pos] == '\n' or body[pos] == ' ' or body[pos] == '\t')) pos += 1;
        if (pos >= body.len) break;
        // Find end of current line.
        var end = pos;
        while (end < body.len and body[end] != '\n') end += 1;
        const line = body[pos..end];
        if (std.mem.startsWith(u8, line, "//") or
            std.mem.startsWith(u8, line, "const std =") or
            std.mem.startsWith(u8, line, "const weld_core =") or
            std.mem.startsWith(u8, line, "const World =") or
            std.mem.startsWith(u8, line, "const ComponentId =") or
            std.mem.startsWith(u8, line, "const FieldDesc =") or
            std.mem.startsWith(u8, line, "const FieldKind =") or
            std.mem.startsWith(u8, line, "const DynamicArchetype =") or
            std.mem.startsWith(u8, line, "const Chunk =") or
            std.mem.startsWith(u8, line, "const comptime_query ="))
        {
            pos = if (end < body.len) end + 1 else end;
            continue;
        }
        break;
    }
    return body[pos..];
}

fn emitProgramsTable(gpa: std.mem.Allocator, buffer: *std.ArrayListUnmanaged(u8), inputs: []const NamedSource, descriptor_flags: []const bool) error{OutOfMemory}!void {
    try buffer.appendSlice(gpa,
        \\pub const Program = struct {
        \\    name: []const u8,
        \\    register: *const fn (world: *World, gpa: std.mem.Allocator) anyerror!void,
        \\    tick: *const fn (world: *World, gpa: std.mem.Allocator) void,
        \\    /// Level-B serialized-IR entry point (M0.8 E4) — emits the
        \\    /// canonical descriptor dump. Null for Level-A-only programs.
        \\    write_descriptors: ?*const fn (gpa: std.mem.Allocator, out: *std.ArrayListUnmanaged(u8)) error{OutOfMemory}!void = null,
        \\};
        \\
        \\pub const programs = [_]Program{
        \\
    );
    for (inputs, descriptor_flags) |in, has_descriptors| {
        const line = if (has_descriptors)
            try std.fmt.allocPrint(gpa, "    .{{ .name = \"{s}\", .register = &{s}.register, .tick = &{s}.tick, .write_descriptors = &{s}.writeDescriptors }},\n", .{ in.name, in.name, in.name, in.name })
        else
            try std.fmt.allocPrint(gpa, "    .{{ .name = \"{s}\", .register = &{s}.register, .tick = &{s}.tick }},\n", .{ in.name, in.name, in.name });
        defer gpa.free(line);
        try buffer.appendSlice(gpa, line);
    }
    try buffer.appendSlice(gpa,
        \\};
        \\
        \\pub fn lookupByName(name: []const u8) ?Program {
        \\    for (programs) |p| if (std.mem.eql(u8, p.name, name)) return p;
        \\    return null;
        \\}
        \\
    );
}
