//! Rule `c_module_isolation` — `*_c` modules may only be imported
//! from files explicitly marked as generated.
//!
//! Canonical formulation from `engine-c-bindings.md §9.2`: any
//! `@import("<lib>_c")` outside a generated file fails the build.
//!
//! A "generated file" is one whose FIRST line carries the `AUTO-GENERATED`
//! marker. Either comment prefix is accepted, `//` or `//!`, because the
//! generators in the tree emit both spellings — a rule taking only one would
//! flag half of them.

const std = @import("std");
const diag = @import("../diagnostic.zig");

const name = "c_module_isolation";

/// Hook called by `main.runLint` once per `.zig` file. Bails out
/// immediately on files marked AUTO-GENERATED (the canonical
/// generated-binding marker — same convention as `doc_comments`);
/// otherwise tokenizes the source and surfaces every
/// `@import("…_c")` occurrence outside that marker.
pub fn check(
    arena: std.mem.Allocator,
    file: []const u8,
    source: [:0]const u8,
    out: *std.ArrayList(diag.Diagnostic),
) !void {
    if (hasAutoGeneratedHeader(source)) return;

    var tokenizer = std.zig.Tokenizer.init(source);
    while (true) {
        const tok = tokenizer.next();
        if (tok.tag == .eof) break;
        if (tok.tag != .builtin) continue;
        if (!std.mem.eql(u8, source[tok.loc.start..tok.loc.end], "@import")) continue;

        const open_paren = tokenizer.next();
        if (open_paren.tag != .l_paren) continue;
        const str = tokenizer.next();
        if (str.tag != .string_literal) continue;

        const raw = source[str.loc.start..str.loc.end];
        if (raw.len < 2 or raw[0] != '"' or raw[raw.len - 1] != '"') continue;
        const content = raw[1 .. raw.len - 1];
        if (!std.mem.endsWith(u8, content, "_c")) continue;

        const pos = diag.lineColFromOffset(source, tok.loc.start);
        try out.append(arena, .{
            .file = file,
            .line = pos.line,
            .col = pos.col,
            .rule = name,
            .message = "imports of `*_c` modules are only allowed from generated files (first-line `// AUTO-GENERATED — DO NOT EDIT` header)",
        });
    }
}

fn hasAutoGeneratedHeader(source: []const u8) bool {
    if (source.len == 0) return false;
    const eol = std.mem.indexOfScalar(u8, source, '\n') orelse source.len;
    const first = source[0..eol];
    if (!std.mem.startsWith(u8, first, "//")) return false;
    return std.mem.indexOf(u8, first, "AUTO-GENERATED") != null;
}
