//! Rule `doc_comments` — every root-level `pub` declaration must
//! carry a `///` doc comment.
//!
//! Canonical formulation in `engine-zig-conventions.md §19` (rules
//! summary, line "Doc comment `///` on every `pub` API — CI —
//! custom linter"). Strategy: parse the file with `std.zig.Ast`,
//! iterate `rootDecls()`, and for each declaration whose first token
//! is `keyword_pub`, verify that the immediately preceding token is a
//! `.doc_comment`.
//!
//! Files that fail to parse are skipped — the compiler will surface
//! the parse error during the normal build, so the linter does not
//! need to duplicate that diagnostic.
//!
//! Generated files (first-line `// AUTO-GENERATED` marker, same
//! convention as `c_module_isolation`) are skipped wholesale: their
//! structure is decided by the bindgen emitter, not by the linter.
//!
//! **Single structural exemption — Zig entry points.** `pub fn main`
//! and `pub fn build(b: *std.Build)` are exempted because their
//! semantics are fixed by Zig itself (the toolchain dispatches them
//! by name, the signature carries no variable contract) and the
//! file-level `//!` doc comment already describes the binary. Acted
//! as an explicit deviation from the brief's *strict-by-default*
//! directive.
//!
//! No other exemption is auto-applied. The brief lists categories of
//! likely false positives (re-exports, type aliases, generic
//! functions returning types, anonymous struct fields) — but the
//! directive is *start strict; iterate via Acted deviations + a
//! Claude.ai roundtrip if real false positives surface*. Encoding
//! those categories as structural exemptions here would replicate the
//! opt-out annotation the brief explicitly lists *Out-of-scope* — it
//! just hides the switch in a different layer.
//!
//! Scope is intentionally narrow: only root-level declarations are
//! checked. Container-internal `pub` (struct methods, nested
//! consts) is out of scope for M0.0 — covered by future stricter
//! rules listed in the brief's *Out-of-scope*.
//!
//! ─────────────────────────────────────────────────────────────────
//!
//! **SECOND ARM — the orphaned doc block.** A `///` run separated from
//! the declaration it documents by an inserted line still satisfies
//! the arm above, because blank lines and plain `//` comments produce
//! no tokens: the token before `pub` is the doc comment either way.
//! So the guard reads a doc as attached while the reader sees it
//! floating, and an edit anchored on a declaration line can split the
//! two without anything going red.
//!
//! WHAT THE COMPILER ALREADY REFUSES, measured with `zig ast-check`
//! rather than assumed, because a rule that claims a compile error is
//! a rule whose power cannot be shown: a doc on a `comptime` block, a
//! doc on a `test` block, a doc in statement position, and an
//! unattached doc at end of file are all hard errors. Those four need
//! no lint. What the compiler ACCEPTS is exactly the orphan class —
//! a `///` run followed by a blank line, or by a plain `//` comment,
//! then its declaration; at root level, inside a container, and on a
//! field alike.
//!
//! SO THE ARM IS LEXICAL AND COVERS BOTH LEVELS. It has to cover
//! container-internal declarations: the instance that motivated it was
//! a method's doc migrated onto a neighbouring method, and the arm
//! above is blind to those by construction.
//!
//! IT IS BLOCKING FROM THE START, and that is a measurement rather
//! than a preference — the tree carries ZERO orphans of this form
//! today, in `src/`, `bench/`, `tests/` and `tools/` alike, so the
//! rule costs no remediation and its whole value is preventive.
//!
//! WHAT IT DOES NOT REACH, named rather than left to be discovered. A
//! doc block that migrated onto a NEIGHBOURING owner with no blank
//! line between the two runs is structurally indistinguishable from
//! one legitimate two-paragraph doc. Catching it means flagging the
//! declaration it robbed, which is a container-level *missing*-doc
//! rule — 1 323 sites on this tree, measured, and a different
//! milestone from one that removes comments.

const std = @import("std");
const Ast = std.zig.Ast;
const diag = @import("../diagnostic.zig");

const name = "doc_comments";

/// Hook called by `main.runLint` once per `.zig` file. Parses with
/// `std.zig.Ast`, walks `rootDecls()`, and flags every `pub` decl
/// whose immediately-preceding token is not a `.doc_comment` — modulo
/// the AUTO-GENERATED header bail-out at the top and the entry-point
/// structural exemption noted in the module header.
pub fn check(
    arena: std.mem.Allocator,
    file: []const u8,
    source: [:0]const u8,
    out: *std.ArrayList(diag.Diagnostic),
) !void {
    if (hasAutoGeneratedHeader(source)) return;

    // Lexical, so it runs before the parse and does not depend on it.
    try checkOrphanDocs(arena, file, source, out);

    var tree = try Ast.parse(arena, source, .zig);
    defer tree.deinit(arena);

    if (tree.errors.len > 0) return;

    const token_tags = tree.tokens.items(.tag);
    const token_starts = tree.tokens.items(.start);

    for (tree.rootDecls()) |decl| {
        const first = tree.firstToken(decl);
        if (token_tags[first] != .keyword_pub) continue;

        if (first > 0 and token_tags[first - 1] == .doc_comment) continue;

        if (isEntryPoint(&tree, source, decl)) continue;

        const offset = token_starts[first];
        const pos = diag.lineColFromOffset(source, offset);
        try out.append(arena, .{
            .file = file,
            .line = pos.line,
            .col = pos.col,
            .rule = name,
            .message = "missing `///` doc comment on public declaration",
        });
    }
}

/// Flag every `///` run that is separated from its declaration by an
/// inserted line.
///
/// A run is a maximal block of consecutive `///` lines. It is an orphan
/// when the line immediately after it is blank or a plain `//` comment
/// — the two forms the compiler accepts and a reader misreads.
///
/// `//!` runs are container docs and are NOT considered: a module
/// header followed by a blank line is the normal shape of every file
/// in the tree, and treating it as an orphan would fire on all of them.
pub fn checkOrphanDocs(
    arena: std.mem.Allocator,
    file: []const u8,
    source: []const u8,
    out: *std.ArrayList(diag.Diagnostic),
) !void {
    var lines: std.ArrayList([]const u8) = .empty;
    defer lines.deinit(arena);
    var split = std.mem.splitScalar(u8, source, '\n');
    while (split.next()) |line| try lines.append(arena, line);

    var i: usize = 0;
    while (i < lines.items.len) {
        if (!isDocLine(lines.items[i])) {
            i += 1;
            continue;
        }
        var end = i;
        while (end + 1 < lines.items.len and isDocLine(lines.items[end + 1])) end += 1;

        if (end + 1 < lines.items.len) {
            const next = std.mem.trim(u8, lines.items[end + 1], " \t\r");
            const separated_by_blank = next.len == 0;
            const separated_by_comment = std.mem.startsWith(u8, next, "//") and
                !std.mem.startsWith(u8, next, "///");
            if (separated_by_blank or separated_by_comment) {
                try out.append(arena, .{
                    .file = file,
                    .line = @intCast(i + 1),
                    .col = 1,
                    .rule = name,
                    .message = if (separated_by_blank)
                        "`///` block separated from its declaration by a blank line — an orphaned doc reads as attached and documents nothing"
                    else
                        "`///` block separated from its declaration by a plain `//` comment — an orphaned doc reads as attached and documents nothing",
                });
            }
        }
        i = end + 1;
    }
}

fn isDocLine(line: []const u8) bool {
    const trimmed = std.mem.trim(u8, line, " \t\r");
    return std.mem.startsWith(u8, trimmed, "///");
}

fn hasAutoGeneratedHeader(source: []const u8) bool {
    if (source.len == 0) return false;
    const eol = std.mem.indexOfScalar(u8, source, '\n') orelse source.len;
    const first = source[0..eol];
    if (!std.mem.startsWith(u8, first, "//")) return false;
    return std.mem.indexOf(u8, first, "AUTO-GENERATED") != null;
}

/// `pub fn main(...)` and `pub fn build(b: *std.Build) void` — Zig
/// entry-point conventions where the file-level `//!` doc usually
/// describes the binary semantics.
fn isEntryPoint(tree: *const Ast, source: []const u8, decl: Ast.Node.Index) bool {
    const token_tags = tree.tokens.items(.tag);
    const token_starts = tree.tokens.items(.start);
    const first = tree.firstToken(decl);

    var idx = first;
    if (idx >= token_tags.len or token_tags[idx] != .keyword_pub) return false;
    idx += 1;
    while (idx < token_tags.len) : (idx += 1) {
        switch (token_tags[idx]) {
            .keyword_inline, .keyword_noinline, .keyword_extern, .keyword_export => continue,
            else => break,
        }
    }
    if (idx >= token_tags.len or token_tags[idx] != .keyword_fn) return false;
    idx += 1;
    if (idx >= token_tags.len or token_tags[idx] != .identifier) return false;

    const start = token_starts[idx];
    // The identifier ends at the first non-identifier byte.
    var end = start;
    while (end < source.len) : (end += 1) {
        const c = source[end];
        const ok = (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or (c >= '0' and c <= '9') or c == '_';
        if (!ok) break;
    }
    const name_slice = source[start..end];
    return std.mem.eql(u8, name_slice, "main") or std.mem.eql(u8, name_slice, "build");
}

// ─── tests ──────────────────────────────────────────────────────────────────

/// Diagnostics from the orphan arm alone.
fn orphansOn(source: []const u8) !usize {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    var diags: std.ArrayList(diag.Diagnostic) = .empty;
    try checkOrphanDocs(arena_state.allocator(), "probe.zig", source, &diags);
    return diags.items.len;
}

/// Diagnostics from BOTH arms, i.e. what `runLint` produces for a file.
fn allOn(source: [:0]const u8) !usize {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    var diags: std.ArrayList(diag.Diagnostic) = .empty;
    try check(arena_state.allocator(), "probe.zig", source, &diags);
    return diags.items.len;
}

test "a doc block directly attached to its declaration is green" {
    try std.testing.expectEqual(@as(usize, 0), try orphansOn(
        \\/// Spawns an entity.
        \\pub fn spawn() void {}
        \\
    ));
}

test "one inserted blank line orphans the block" {
    try std.testing.expectEqual(@as(usize, 1), try orphansOn(
        \\/// Spawns an entity.
        \\
        \\pub fn spawn() void {}
        \\
    ));
}

test "one inserted plain comment orphans the block" {
    try std.testing.expectEqual(@as(usize, 1), try orphansOn(
        \\/// Spawns an entity.
        \\// a probe someone left here
        \\pub fn spawn() void {}
        \\
    ));
}

test "the arm covers container-internal declarations, not only root ones" {
    // The instance that motivated this arm was a method's doc, and the
    // pre-existing arm reads `rootDecls()` only — so an arm that also
    // looked at root level alone would have missed the very case it
    // exists for.
    try std.testing.expectEqual(@as(usize, 1), try orphansOn(
        \\pub const World = struct {
        \\    /// Spawns an entity.
        \\
        \\    pub fn spawn(self: *World) void {
        \\        _ = self;
        \\    }
        \\};
        \\
    ));
    try std.testing.expectEqual(@as(usize, 1), try orphansOn(
        \\pub const Body = struct {
        \\    /// Mass in kilograms.
        \\
        \\    mass: f32 = 1,
        \\};
        \\
    ));
}

test "a `//!` container header followed by a blank line is not an orphan" {
    // Non-vacuity control for every test above: `//!` then a blank line is
    // the shape of every file header in the tree, so an arm that did not
    // distinguish the two sigils would fire 275 times and its other tests
    // would still pass.
    try std.testing.expectEqual(@as(usize, 0), try orphansOn(
        \\//! Module header.
        \\//! Second line of it.
        \\
        \\const std = @import("std");
        \\
    ));
}

test "of two runs separated by a blank line, the first is the orphan" {
    try std.testing.expectEqual(@as(usize, 1), try orphansOn(
        \\/// A run that lost its owner.
        \\
        \\/// The run that kept it.
        \\pub fn spawn() void {}
        \\
    ));
}

test "the diagnostic names which separator split the block" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var blank: std.ArrayList(diag.Diagnostic) = .empty;
    try checkOrphanDocs(arena, "probe.zig", "/// d\n\npub fn f() void {}\n", &blank);
    try std.testing.expectEqual(@as(usize, 1), blank.items.len);
    try std.testing.expect(std.mem.indexOf(u8, blank.items[0].message, "blank line") != null);
    try std.testing.expectEqual(@as(u32, 1), blank.items[0].line);

    var plain: std.ArrayList(diag.Diagnostic) = .empty;
    try checkOrphanDocs(arena, "probe.zig", "/// d\n// x\npub fn f() void {}\n", &plain);
    try std.testing.expectEqual(@as(usize, 1), plain.items.len);
    try std.testing.expect(std.mem.indexOf(u8, plain.items[0].message, "plain `//` comment") != null);
}

test "the six splits of the hybrid-storage milestone, reconstructed" {
    // FORM ONE — five of the six. An edit anchored on the declaration line
    // left the declaration carrying a plain `//` where its `///` belonged.
    // The pre-existing arm catches these, and this pins that it still does.
    try std.testing.expectEqual(@as(usize, 1), try allOn(
        \\// Spawns an entity.
        \\pub fn spawn() void {}
        \\
    ));
    // Same shape with the doc pushed away from its owner by an insertion, and
    // here is the whole reason the second arm exists: exactly ONE diagnostic
    // fires, and it is the orphan arm's. The original arm stays silent because
    // blank lines and plain `//` comments produce no tokens, so the token before
    // `pub` is still the doc comment — the guard reads the doc as attached.
    //
    // Asserted on the MESSAGE and not on the count: a count of one is also what
    // a tree with only the original arm would report if the doc had vanished
    // entirely, and this test would then pass while measuring the wrong arm.
    {
        var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
        defer arena_state.deinit();
        var diags: std.ArrayList(diag.Diagnostic) = .empty;
        try check(arena_state.allocator(), "probe.zig",
            \\/// Spawns an entity.
            \\
            \\// a probe someone left here
            \\pub fn spawn() void {}
            \\
        , &diags);
        try std.testing.expectEqual(@as(usize, 1), diags.items.len);
        try std.testing.expect(std.mem.indexOf(u8, diags.items[0].message, "separated from its declaration") != null);
        try std.testing.expect(std.mem.indexOf(u8, diags.items[0].message, "missing") == null);
    }

    // FORM TWO — the sixth, and the arm does NOT reach it. A doc block that
    // migrated onto a neighbouring owner, with no line between the two runs,
    // is byte-for-byte one legitimate two-paragraph doc. Below,
    // `wasDedupNeeded`'s doc is really `isTableDriven`'s, and `isTableDriven`
    // is left with none — but it is container-internal, which the original
    // arm does not read.
    //
    // Asserted as ZERO on purpose: a test claiming this is caught would be a
    // text that affirms more than its oracle establishes. Closing it means a
    // container-level MISSING-doc rule, 1 323 sites on this tree.
    // The container carries its own doc, so the only thing this fixture can
    // report is the property under test — without it the original arm fires on
    // `pub const QueryPlan` and the zero would be measuring the wrong absence.
    try std.testing.expectEqual(@as(usize, 0), try allOn(
        \\/// The plan a mixed query is walked under.
        \\pub const QueryPlan = struct {
        \\    /// True when the term is served by the archetype walk.
        \\    /// True when the per-entity admission needs a dedup table.
        \\    pub fn wasDedupNeeded(self: *const QueryPlan) bool {
        \\        _ = self;
        \\        return false;
        \\    }
        \\    pub fn isTableDriven(self: *const QueryPlan) bool {
        \\        _ = self;
        \\        return true;
        \\    }
        \\};
        \\
    ));
}

test "a generated file is exempt from both arms" {
    try std.testing.expectEqual(@as(usize, 0), try allOn(
        \\// AUTO-GENERATED — DO NOT EDIT
        \\/// A doc the emitter placed.
        \\
        \\pub fn emitted() void {}
        \\
    ));
}
