//! Rule `doc_comments` — every root-level `pub` declaration must
//! carry a `///` doc comment.
//!
//! `engine-zig-conventions.md §12, §19` make doc comments mandatory on
//! every public API surface. Strategy: parse the file with
//! `std.zig.Ast`, iterate `rootDecls()`, and for each declaration
//! whose first token is `keyword_pub`, verify that the immediately
//! preceding token is a `.doc_comment`.
//!
//! Files that fail to parse are skipped — the compiler will surface
//! the parse error during the normal build, so the linter does not
//! need to duplicate that diagnostic.
//!
//! Generated files (first-line `// AUTO-GENERATED` marker, same
//! convention as `c_module_isolation`) are skipped wholesale: their
//! structure is decided by the bindgen emitter, not by the linter.
//!
//! The rule applies the four structural exemptions the brief's
//! *Notes* explicitly anticipates as false positives:
//!   - **Pure re-exports** `pub const X = expr;` whose initialiser is
//!     a bare identifier or a `mod.ident` chain. The doc lives on the
//!     source declaration; the re-export adds no new contract.
//!   - **Type aliases** `pub const X = struct/enum/union/opaque {...}`
//!     where the initialiser is a type-literal expression.
//!   - **Generic functions returning `type`**: `pub fn X(comptime ...) type`.
//!     Their callable surface is the type they produce — the docs
//!     belong on that type, not on the comptime factory.
//!   - **Entry points** `pub fn main(...)` and `pub fn build(b: *std.Build)`
//!     — semantics fixed by Zig itself, file-level `//!` doc usually
//!     covers the binary.
//!
//! These exemptions are NOT opt-out annotations (no `// weld-lint:*`
//! comments). They are structural patterns the brief calls out and
//! the runner never visits container-internal `pub`.
//!
//! Scope is intentionally narrow: only root-level declarations are
//! checked. Container-internal `pub` (struct methods, nested
//! consts) is out of scope for M0.0 — covered by future stricter
//! rules listed in the brief's *Out-of-scope*.

const std = @import("std");
const Ast = std.zig.Ast;
const diag = @import("../diagnostic.zig");

pub const name = "doc_comments";

pub fn check(
    arena: std.mem.Allocator,
    file: []const u8,
    source: [:0]const u8,
    out: *std.ArrayList(diag.Diagnostic),
) !void {
    if (hasAutoGeneratedHeader(source)) return;

    var tree = try Ast.parse(arena, source, .zig);
    defer tree.deinit(arena);

    if (tree.errors.len > 0) return;

    const token_tags = tree.tokens.items(.tag);
    const token_starts = tree.tokens.items(.start);

    for (tree.rootDecls()) |decl| {
        const first = tree.firstToken(decl);
        if (token_tags[first] != .keyword_pub) continue;

        if (first > 0 and token_tags[first - 1] == .doc_comment) continue;

        if (isExemptDecl(&tree, source, decl)) continue;

        const offset = token_starts[first];
        const pos = diag.lineColFromOffset(source, offset);
        try out.append(arena, .{
            .file = file,
            .line = pos.line,
            .col = pos.col,
            .rule = name,
            .message = "missing `///` doc comment on public declaration",
        });
    }
}

fn hasAutoGeneratedHeader(source: []const u8) bool {
    if (source.len == 0) return false;
    const eol = std.mem.indexOfScalar(u8, source, '\n') orelse source.len;
    const first = source[0..eol];
    if (!std.mem.startsWith(u8, first, "//")) return false;
    return std.mem.indexOf(u8, first, "AUTO-GENERATED") != null;
}

/// Dispatcher for the four structural exemptions the brief's *Notes*
/// anticipates. Returns true if `decl` matches any one of them.
fn isExemptDecl(tree: *const Ast, source: []const u8, decl: Ast.Node.Index) bool {
    if (isPureReExport(tree, decl)) return true;
    if (isTypeAlias(tree, decl)) return true;
    if (isGenericReturningType(tree, decl)) return true;
    if (isEntryPoint(tree, source, decl)) return true;
    return false;
}

/// `pub const X = <ident-chain>;` or `pub const X = @import("…");` —
/// the initialiser is either a bare identifier / member-access chain
/// or a single `@import(…)` builtin call. Both are pure re-exports;
/// the doc belongs on the source declaration.
fn isPureReExport(tree: *const Ast, decl: Ast.Node.Index) bool {
    const token_tags = tree.tokens.items(.tag);
    const first = tree.firstToken(decl);
    const last = tree.lastToken(decl);

    var idx = first;
    if (idx >= token_tags.len or token_tags[idx] != .keyword_pub) return false;
    idx += 1;
    if (idx >= token_tags.len or token_tags[idx] != .keyword_const) return false;
    idx += 1;
    if (idx >= token_tags.len or token_tags[idx] != .identifier) return false;
    idx += 1;
    if (idx >= token_tags.len or token_tags[idx] != .equal) return false;
    idx += 1;

    // Case A — `@import("…")`. Accept the canonical shape.
    if (idx <= last and token_tags[idx] == .builtin and
        std.mem.eql(u8, tree.tokenSlice(idx), "@import"))
    {
        return true;
    }

    // Case B — identifier-chain.
    while (idx <= last) : (idx += 1) {
        const tag = token_tags[idx];
        switch (tag) {
            .identifier, .period, .semicolon => {},
            else => return false,
        }
    }
    return true;
}

/// `pub const X = struct/enum/union/opaque/packed/extern …` — the
/// initialiser is a type literal. Doc comments belong on the type
/// itself or its members, not on the alias keyword.
fn isTypeAlias(tree: *const Ast, decl: Ast.Node.Index) bool {
    const token_tags = tree.tokens.items(.tag);
    const first = tree.firstToken(decl);

    var idx = first;
    if (idx >= token_tags.len or token_tags[idx] != .keyword_pub) return false;
    idx += 1;
    if (idx >= token_tags.len or token_tags[idx] != .keyword_const) return false;
    idx += 1;
    if (idx >= token_tags.len or token_tags[idx] != .identifier) return false;
    idx += 1;
    // Skip optional `: T` type ascription.
    if (idx < token_tags.len and token_tags[idx] == .colon) {
        idx += 1;
        while (idx < token_tags.len and token_tags[idx] != .equal) : (idx += 1) {}
    }
    if (idx >= token_tags.len or token_tags[idx] != .equal) return false;
    idx += 1;

    if (idx >= token_tags.len) return false;
    // Walk through optional layout/packing modifiers before the
    // container keyword: `extern`, `packed`.
    while (idx < token_tags.len) : (idx += 1) {
        switch (token_tags[idx]) {
            .keyword_extern, .keyword_packed => continue,
            .keyword_struct, .keyword_enum, .keyword_union, .keyword_opaque, .keyword_error => return true,
            else => return false,
        }
    }
    return false;
}

/// `pub fn Name(...) type {...}` — a generic function whose return
/// type is the literal token `type`. The brief lists "generic
/// functions returning types" as an expected false positive.
fn isGenericReturningType(tree: *const Ast, decl: Ast.Node.Index) bool {
    const token_tags = tree.tokens.items(.tag);
    const first = tree.firstToken(decl);

    var idx = first;
    if (idx >= token_tags.len or token_tags[idx] != .keyword_pub) return false;
    idx += 1;
    // Optional `inline` / `noinline` / `extern` / `export` qualifiers.
    while (idx < token_tags.len) : (idx += 1) {
        switch (token_tags[idx]) {
            .keyword_inline, .keyword_noinline, .keyword_extern, .keyword_export => continue,
            else => break,
        }
    }
    if (idx >= token_tags.len or token_tags[idx] != .keyword_fn) return false;
    idx += 1;
    if (idx >= token_tags.len or token_tags[idx] != .identifier) return false;
    idx += 1;
    if (idx >= token_tags.len or token_tags[idx] != .l_paren) return false;

    // Skip balanced parens of the parameter list.
    var depth: u32 = 1;
    idx += 1;
    while (idx < token_tags.len and depth > 0) : (idx += 1) {
        switch (token_tags[idx]) {
            .l_paren => depth += 1,
            .r_paren => depth -= 1,
            else => {},
        }
    }
    // Skip optional `align(...)`, `linksection(...)`, `callconv(...)`
    // before the return type. Each consumes balanced parens.
    while (idx < token_tags.len) {
        const tag = token_tags[idx];
        if (tag == .keyword_align or tag == .keyword_linksection or tag == .keyword_callconv) {
            idx += 1;
            if (idx >= token_tags.len or token_tags[idx] != .l_paren) return false;
            depth = 1;
            idx += 1;
            while (idx < token_tags.len and depth > 0) : (idx += 1) {
                switch (token_tags[idx]) {
                    .l_paren => depth += 1,
                    .r_paren => depth -= 1,
                    else => {},
                }
            }
            continue;
        }
        break;
    }
    // The next non-trivial token must be the return type. We accept
    // an identifier whose text equals `"type"` — `type` is lexed as
    // `.identifier` in Zig, not as a keyword.
    if (idx >= token_tags.len) return false;
    if (token_tags[idx] != .identifier) return false;
    return std.mem.eql(u8, tree.tokenSlice(idx), "type");
}

/// `pub fn main(...)` and `pub fn build(b: *std.Build) void` — Zig
/// entry-point conventions where the file-level `//!` doc usually
/// describes the binary semantics.
fn isEntryPoint(tree: *const Ast, source: []const u8, decl: Ast.Node.Index) bool {
    const token_tags = tree.tokens.items(.tag);
    const token_starts = tree.tokens.items(.start);
    const first = tree.firstToken(decl);

    var idx = first;
    if (idx >= token_tags.len or token_tags[idx] != .keyword_pub) return false;
    idx += 1;
    while (idx < token_tags.len) : (idx += 1) {
        switch (token_tags[idx]) {
            .keyword_inline, .keyword_noinline, .keyword_extern, .keyword_export => continue,
            else => break,
        }
    }
    if (idx >= token_tags.len or token_tags[idx] != .keyword_fn) return false;
    idx += 1;
    if (idx >= token_tags.len or token_tags[idx] != .identifier) return false;

    const start = token_starts[idx];
    // The identifier ends at the first non-identifier byte.
    var end = start;
    while (end < source.len) : (end += 1) {
        const c = source[end];
        const ok = (c >= 'a' and c <= 'z') or (c >= 'A' and c <= 'Z') or (c >= '0' and c <= '9') or c == '_';
        if (!ok) break;
    }
    const name_slice = source[start..end];
    return std.mem.eql(u8, name_slice, "main") or std.mem.eql(u8, name_slice, "build");
}
