#!/usr/bin/env sh
# Validate the title line of a commit message against the Conventional Commits
# subset enforced by Weld. See briefs/S0-bootstrap.md, section
# "scripts/check-commit-msg.sh specification" for the canonical rules.
#
# Usage: check-commit-msg.sh <path-to-commit-message-file>
#
# POSIX strict — must run under dash (Debian/Ubuntu /bin/sh) and Git Bash on
# Windows. No bashisms.

set -eu

print_error() {
    bad_title="$1"
    {
        echo "error: invalid commit message title:"
        echo "    $bad_title"
        echo ""
        echo "Expected Conventional Commits format:"
        echo "    <type>(<scope>)?!?: <description>"
        echo ""
        echo "  type         one of: feat, fix, perf, refactor, test, docs, chore, breaking"
        echo "  scope        optional, matches [a-z0-9-]+"
        echo "  !            optional, marks a breaking change"
        echo "  description  1-72 chars, lowercase first letter, no trailing period"
        echo ""
        echo "Example:"
        echo "    feat(build): add zig version guard"
    } >&2
}

if [ "$#" -lt 1 ]; then
    echo "error: missing commit message file argument" >&2
    exit 1
fi

msg_file="$1"

if [ ! -f "$msg_file" ]; then
    echo "error: commit message file not found: $msg_file" >&2
    exit 1
fi

# Read the first non-empty, non-comment line as the title.
title=""
while IFS= read -r line; do
    case "$line" in
        '#'*) continue ;;
    esac
    if [ -n "$line" ]; then
        title="$line"
        break
    fi
done < "$msg_file"

if [ -z "$title" ]; then
    echo "error: empty commit message" >&2
    exit 1
fi

# Bypass validation for merges, reverts, and autogenerated fixup/squash markers.
case "$title" in
    "Merge "*|"Revert "*|"fixup!"*|"squash!"*) exit 0 ;;
esac

types='feat|fix|perf|refactor|test|docs|chore|breaking'
prefix_re="^($types)(\([a-z0-9-]+\))?!?: "
full_re="${prefix_re}[a-z]"

if ! printf '%s' "$title" | grep -Eq "$full_re"; then
    print_error "$title"
    exit 1
fi

# Extract the description part (everything after the prefix).
description=$(printf '%s' "$title" | sed -E "s/${prefix_re}//")

desc_len=${#description}
if [ "$desc_len" -lt 1 ] || [ "$desc_len" -gt 72 ]; then
    echo "error: description is $desc_len chars, must be 1-72" >&2
    print_error "$title"
    exit 1
fi

case "$description" in
    *.) print_error "$title"; exit 1 ;;
esac

exit 0
